### ISSUE TITLE
Can this package be used as a drop in replacement?

### ISSUE THREAD

**Issue by lquessenberry** [knapsack-cloud/twig-renderer#124]
I have been working on a project that uses Patternlab PHP. Unfortunately that has been archived for support. I am wondering if this renderer will work better. Has anyone tried this?

**Comment by hadl** [comment]
Drop in replacement? No.
As far as i know Patternlab PHP uses mustache templates and this is the for Twig-Renderer via Node.

So if you switch to Twig-Templates in your Patternlab then you should be good to go with a fresh installation of the  current version of Patternlab and "engine-twig-php".
Keeping the mustache templates you should go with "engine-mustache".
