### ISSUE TITLE
Using twig's `with` tag breaks template rendering with Twig v.1.41.

### ISSUE THREAD

**Issue by a-fro** [knapsack-cloud/twig-renderer#37]
I get the following error in my terminal unless I remove the `with` tag when including other templates: 
```
PHP TwigRenderer Error: The response callback is expected to resolve with an object implementing Psr\Http\Message\ResponseInterface, but rejected with "Error" instead.
null
```
I am able to get the templates to render correctly by pinning my Twig dependency to `v.1.36`.

**Comment by sghoweri** [comment]
+1. We’ve run into this same issue on our end as well.

**Comment by sghoweri** [comment]
For reference: https://github.com/bolt-design-system/bolt/issues/1175

**Comment by EvanLovely** [comment]
All fixed now!
